### ISSUE TITLE
Upgrade `@walletconnect/*` deps to `2.x.x` stable

### ISSUE THREAD

**Issue by bkrem** [WalletConnect/chat-client-js#9]
- [ ] Upgrade `@walletconnect/*` deps 
- [ ]  Use shared `core.history` instead of custom history controller (same change as for `core.history` [in this PR](https://github.com/WalletConnect/auth-client-js/pull/45/files#diff-9b059223de3447b07a53eadf2152670d10f4dbcfb2a30f2726809f17de92b7acR224))
- [ ] Remove custom `history` controller

**Comment by devceline** [comment]
Closing this as it was already closed by https://github.com/WalletConnect/chat-client-js/pull/15
